=== jonander2233/DAMLenguajesDeMarcas/UD3/Ejercicio_13_xsd/componentes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="componentes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="listacomponentes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="componente" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:choice>
                      <xs:element name="tarjetagrafica">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="memoria" type="xs:string"/>
                            <xs:element name="precio">
                              <xs:complexType>
                                <xs:simpleContent>
                                  <xs:extension base="xs:decimal">
                                    <xs:attribute name="moneda" type="xs:string"/>
                                  </xs:extension>
                                </xs:simpleContent>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="monitor">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="tamanio" type="xs:decimal"/>
                            <xs:element name="precio">
                              <xs:complexType>
                                <xs:simpleContent>
                                  <xs:extension base="xs:decimal">
                                    <xs:attribute name="moneda" type="xs:string"/>
                                  </xs:extension>
                                </xs:simpleContent>
                              </xs:complexType>
                            </xs:element>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>
                  </xs:sequence>
                  <xs:attribute name="codigo" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jonander2233/DAMLenguajesDeMarcas/UD3/Ejercicio_13_xsd/componentes.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentes xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="componentes.xsd">
    <listacomponentes>
        <componente>
          <tarjetagrafica>
            <memoria>2GB</memoria>
            <precio moneda="euros">190</precio>
          </tarjetagrafica>
        </componente>
        <componente codigo="123456">
          <monitor>
            <tamanio>14</tamanio>
            <precio moneda="euros">99.49</precio>
          </monitor>
        </componente>
    </listacomponentes>
</componentes>
