<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas [
    <!ELEMENT listaventas (venta+)>
    <!ELEMENT venta (importe,comprador,vendedor,fecha?,codigofactura)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codigofactura (#PCDATA)>
    ]
>
<listaventas>
    <venta>
        <importe></importe>
        <comprador></comprador>
        <vendedor></vendedor>
        <fecha></fecha>
        <codigofactura></codigofactura>
    </venta>
    <venta>
        <importe></importe>
        <comprador></comprador>
        <vendedor></vendedor>
        <codigofactura></codigofactura>
    </venta>
</listaventas>